config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  root to: 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :message, :presence => true

  belongs_to :user
  after_create_commit { PostRelayJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(crop_params)
    if post.save
      flash[:success] = "Your post was successfully created."
      redirect_to posts_path
    else
      flash[:error] = "Something went wrong creating your post."
      render :new
    end
  end

  private

  def crop_params
    params.require(:post).permit(:title, :message, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snipehunter</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, remote: true do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, :class => "form-control" %>
  </fieldset>
  <%= f.submit "Create Post", class: "btn btn-default btn-sm" %>
<% end %>

app/views/posts/index.erb
<div class="page-header">
  <p class="pull-right">Logged in as <%= current_user.email %></p>
</div>

<div class="page-header">
  <h1>Live Feed Messages - Awesomeness</h1>
</div>

<ul class='posts'>
  <% @posts.each do |post| %>
    <li class="">
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Add New Post", new_post_path, class: 'btn btn-default' %>
</div>

app/views/posts/new.html.erb
<h1>Add new message</h1>
<%= render 'form' %>

app/views/posts/show.erb
<h1><%= @post.title %></h1>

<p><%= @post.message %></p>

<p><%= @post.updated_at %></p>

<button class="btn btn-primary btn-sm"><%= link_to 'Back', posts_path %></button>